### ISSUE TITLE
Bitrot: Invalid dictionary & modes

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-br-fr#4]
`Error: Invalid dictionary (hint: entry on the right beginning with whitespace)`

`cp: cannot stat '*.mode': No such file or directory`

**Comment by TinoDidriksen** [comment]
Nope, didn't fix the whole issue.

**Comment by ftyers** [comment]
wfm:

```
fran@ipek:~/source/apertium/pairs/apertium-br-fr$ echo "P'edon war bont an Naoned" | apertium -d . br-fr
Quand  sur le pont de Nantes
```

**Comment by mr-martian** [comment]
It now compiles for me on latest lttoolbox.
