### ISSUE TITLE
Switch to new-style transfer ?

### ISSUE THREAD

**Issue by ygorg** [apertium/apertium-br-fr#6]
When using modes from this repo using `apertium-python` the results are weirdly formatted.
I think this is linked to new/old style transfer which is dealt with in the apertium CLI in [apertium/wblank-mode.cc#L67](https://github.com/apertium/apertium/blob/b1fd917089ae5d2f3953d05fdd1682b89993d2d2/apertium/wblank-mode.cc#L67).

I don't know if the solution is to change `modes.xml` (`apertium-transfer * autobil.bin` to `lt-proc -b autobil.bin | apertium_transfer *`) or to change `apertium-python` (see https://github.com/ygorg/apertium-python/commit/9fcace1c38c09ee3cb6147e773285771aa851ca4).

```python
# apertium-python
import apertium
apertium.translate('br', 'fr', "P'edon war bont an Naoned")
# '@pa je #/tre @war @an #/ont de  @Naoned@'
```

```bash
# apertium CLI
echo "P'edon war bont an Naoned" | apertium br-fr
# Quand j'étais sur le pont de  Nantes
```

**Comment by TinoDidriksen** [comment]
Yes, we should do this for all repos. We can script the conversion and get it done in a single run.

**Comment by ygorg** [comment]
This modification only concerns the `modes.xml` files or does it concern other files ?

**Comment by TinoDidriksen** [comment]
Only `modes.xml`
